### ISSUE TITLE
Very slow for first generation

### ISSUE THREAD

**Issue by serdarozturk88** [mbknor/mbknor-jackson-jsonSchema#67] opened 2018-04-27 06:37 UTC
Hi,
In an spring boot application when i generate class schema for the first time, it takes too long(approximately 12-13 seconds) to create json schema string.

I wonder what is taking time(classpath scanning, some initialization code vs.)

Thanks

**Comment by mbknor** [comment] 2018-04-27 08:42
Hi,

This problem is caused by this line:

https://github.com/mbknor/mbknor-jackson-jsonSchema/blob/master/src/main/scala/com/kjetland/jackson/jsonSchema/JsonSchemaGenerator.scala#L22

It scans the entire classpath. An improvement would be to make this configruable.
A PR fixing this would be great 😀

**Comment by serdarozturk88** [comment] 2018-04-27 10:48
Thanks for your answer.

Could you please give some details about this making configurable.

In which cases the entire classpath should be scanned ?
Should i filter the scan root or disable scan according to config?
İf we disable this which features won't work?

**Comment by xenoterracide** [comment] 2018-04-30 03:43
not the OP, but
> In which cases the entire classpath should be scanned ?

none, not ever, bad idea, ask the developer to provide a package name from which to start scanning so you don't end up scanning every library ever, Possibly have an annotation (like spring boot does) to say where classpath scanning should start. Also possibly make it possible not to scan, instead simply provide a list of classes.

**Comment by zrrobbins** [comment] 2018-08-30 22:07
Yeah, this issue makes the library almost unusable for large projects, not only slowing things down to a crawl, but causing OOM failures.

**Comment by mbknor** [comment] 2018-08-31 07:06
I'm Not currently using this library on a daily basis anymore, but i'll try to get time to fix this

**Comment by mbknor** [comment] 2018-09-02 22:13
Any feedback on https://github.com/mbknor/mbknor-jackson-jsonSchema/pull/75 would be apreciated

**Comment by mbknor** [comment] 2018-09-22 14:59
Fixed in https://github.com/mbknor/mbknor-jackson-jsonSchema/commit/5391586ad9309f5029dd5097cfe41ed9fc69701e

**Closed by mbknor** 2018-09-22 14:59 UTC
Labels: help wanted

**Comment by mbknor** [comment] 2018-09-22 15:52
Fixed in version to 1.0.30
