### ISSUE TITLE
Title attribute being set to null when more than 2 definitions added

### ISSUE THREAD

**Issue by AlexMALReis** [mbknor/mbknor-jackson-jsonSchema#63] opened 2018-02-28 15:38 UTC
Good afternoon.

I have the following pojo :

```java

public class AccountingEntryRequestTO {

    public enum MovementType {

        ALL(1),
        CLAIMS(2),
        POLICIES(3);

        private Integer intValue;
        private static Map<Integer, MovementType> map = new HashMap<>();

        MovementType(Integer intValue){
            this.intValue = intValue;
        }

        static {
            for (MovementType type : MovementType.values()) {
                map.put(type.intValue, type);
            }
        }

        public static MovementType valueOf(int type) {
            return map.get(type);
        }

        public Integer getIntValue(){
            return this.intValue;
        }

    }

    @JsonProperty("job-instance.label.email")
    private String email;

    @JsonProperty("job-instance.label.initialDate")
    private Date initialDate;

    @JsonProperty("job-instance.label.endDate")
    private Date finishDate;

    @JsonProperty("job-instance.label.attach")
    private Boolean attach;

    @JsonProperty("job-instance.label.periodicity")
    private EntryMovementPeriodicityType periodicity;

    @JsonProperty("job-instance.label.movementType")
    private MovementType movementType;

    @JsonProperty(value = "DynamicCombo", required = true)
    private List<DynamicCombo> dynamicCombo;

```
**DynamicCombo as following**

```java 
@Getter
@Setter
@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, include = JsonTypeInfo.As.PROPERTY, property = "type")
@JsonSubTypes({
        @JsonSubTypes.Type(value = DynamicComboCompanies.class, name="job-instance.label.company"),
        @JsonSubTypes.Type(value = DynamicComboJournalTypes.class, name="job-instance.label.journalType"),
        @JsonSubTypes.Type(value = DynamicComboProducts.class, name="job-instance.label.product")}
)
public abstract class DynamicCombo {

    @JsonProperty("value")
    private String value;

}

```
**And finally the generated json :**

```json
{
  "$schema" : "http://json-schema.org/draft-04/schema#",
  "title" : "Accounting Entry Request TO",
  "type" : "object",
  "additionalProperties" : false,
  "properties" : {
    "job-instance.label.email" : {
      "type" : "string"
    },
    "job-instance.label.initialDate" : {
      "type" : "integer",
      "format" : "utc-millisec"
    },
    "job-instance.label.endDate" : {
      "type" : "integer",
      "format" : "utc-millisec"
    },
    "job-instance.label.attach" : {
      "type" : "boolean"
    },
    "job-instance.label.periodicity" : {
      "type" : "string",
      "enum" : [ "DAILY", "MONTHLY" ]
    },
    "DynamicCombo" : {
      "type" : "array",
      "items" : {
        "oneOf" : [ {
          "$ref" : "#/definitions/DynamicComboCompanies"
        }, {
          "$ref" : "#/definitions/DynamicComboJournalTypes"
        }, {
          "$ref" : "#/definitions/DynamicComboProducts"
        } ]
      }
    }
  },
  "required" : [ "DynamicCombo" ],
  "definitions" : {
    "DynamicComboCompanies" : {
      "type" : "object",
      "additionalProperties" : false,
      "properties" : {
        "type" : {
          "type" : "string",
          "enum" : [ null ],
          "default" : null
        },
        "value" : {
          "type" : "string"
        }
      },
      **"title" : null,**
      "required" : [ "type" ]
    },
    "DynamicComboJournalTypes" : {
      "type" : "object",
      "additionalProperties" : false,
      "properties" : {
        "type" : {
          "type" : "string",
          "enum" : [ null ],
          "default" : null
        },
        "value" : {
          "type" : "string"
        }
      },
      **"title" : null,**
      "required" : [ "type" ]
    },
    "DynamicComboProducts" : {
      "type" : "object",
      "additionalProperties" : false,
      "properties" : {
        "type" : {
          "type" : "string",
          "enum" : [ null ],
          "default" : null
        },
        "value" : {
          "type" : "string"
        }
      },
      **"title" : null,**
      "required" : [ "type" ]
    }
  }
}

```
As you can see the title attribute is not being set. The enum attribute is not being set either but I dont know the consequences.

Thanks in advance for any help.

**Comment by mbknor** [comment] 2018-03-15 23:36
This is strange.

This looks like this test, where I test Lists using polymorphism:

https://github.com/mbknor/mbknor-jackson-jsonSchema/blob/cd36350315d6eef6d0d61542a8d16653d14b368b/src/test/scala/com/kjetland/jackson/jsonSchema/JsonSchemaGeneratorTest.scala#L646

It gives the following schema - which, as you can see, correctly shows both title and enum:

```json
{
  "$schema" : "http://json-schema.org/draft-04/schema#",
  "title" : "Pojo With Arrays",
  "type" : "object",
  "additionalProperties" : false,
  "properties" : {
    "intArray1" : {
      "type" : "array",
      "items" : {
        "type" : "integer"
      }
    },
    "stringArray" : {
      "type" : "array",
      "items" : {
        "type" : "string"
      }
    },
    "stringList" : {
      "type" : "array",
      "minItems" : 1,
      "maxItems" : 10,
      "items" : {
        "type" : "string"
      }
    },
    "polymorphismList" : {
      "type" : "array",
      "items" : {
        "oneOf" : [ {
          "$ref" : "#/definitions/Child1"
        }, {
          "$ref" : "#/definitions/Child2"
        } ]
      }
    },
    "polymorphismArray" : {
      "type" : "array",
      "items" : {
        "oneOf" : [ {
          "$ref" : "#/definitions/Child1"
        }, {
          "$ref" : "#/definitions/Child2"
        } ]
      }
    },
    "regularObjectList" : {
      "type" : "array",
      "items" : {
        "$ref" : "#/definitions/ClassNotExtendingAnything"
      }
    },
    "listOfListOfStrings" : {
      "type" : "array",
      "items" : {
        "type" : "array",
        "items" : {
          "type" : "string"
        }
      }
    },
    "setOfUniqueValues" : {
      "type" : "array",
      "items" : {
        "type" : "string",
        "enum" : [ "E", "B", "A", "D", "C" ]
      }
    }
  },
  "required" : [ "intArray1", "stringArray", "stringList", "polymorphismList", "polymorphismArray", "regularObjectList", "listOfListOfStrings", "setOfUniqueValues" ],
  "definitions" : {
    "Child1" : {
      "type" : "object",
      "additionalProperties" : false,
      "properties" : {
        "type" : {
          "type" : "string",
          "enum" : [ "child1" ],
          "default" : "child1"
        },
        "parentString" : {
          "type" : "string"
        },
        "child1String" : {
          "type" : "string"
        },
        "_child1String2" : {
          "type" : "string"
        },
        "_child1String3" : {
          "type" : "string"
        }
      },
      "title" : "child1",
      "required" : [ "type", "_child1String3" ]
    },
    "Child2" : {
      "type" : "object",
      "additionalProperties" : false,
      "properties" : {
        "type" : {
          "type" : "string",
          "enum" : [ "child2" ],
          "default" : "child2"
        },
        "parentString" : {
          "type" : "string"
        },
        "child2int" : {
          "type" : "integer"
        }
      },
      "title" : "child2",
      "required" : [ "type" ]
    },
    "ClassNotExtendingAnything" : {
      "type" : "object",
      "additionalProperties" : false,
      "properties" : {
        "someString" : {
          "type" : "string"
        },
        "myEnum" : {
          "type" : "string",
          "enum" : [ "E", "B", "A", "D", "C" ],
          "JsonSchemaInjectOnEnum" : true
        }
      }
    }
  }
}
```

If you still have this problem, I think you have to create a PR with testcase showing the problem..

**Comment by mbknor** [comment] 2018-04-11 06:01
Can you please follow up this one,  @AlexMALReis ? If not, I'll close it as not a bug ref my last comment

**Comment by mbknor** [comment] 2018-04-30 11:53
Not a bug

**Closed by mbknor** 2018-04-30 11:53 UTC
